// Package weather stuff ...
package weather

// CurrentCondition ...
var CurrentCondition string
// CurrentLocation ...
var CurrentLocation string

// Forecast function does something ...
func Forecast(city, condition string) string {
	CurrentLocation, CurrentCondition = city, condition
	return CurrentLocation + " - current weather condition: " + CurrentCondition
}
